# Generated by Django 6.0.3 on 2026-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
